# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

# Configure which branches trigger builds
trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - .azure/*
    - LICENSE.md
    - README.md

# Run PR validation on all branches
pr:
  autoCancel: true
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud New'
    organization: 'madd0'
    scannerMode: 'MSBuild'
    projectKey: 'madd0_AzureStorageDriver'
    projectName: 'madd0.AzureStorageDriver'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.organization=madd0

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:BaseOutputPath=$(Build.BinariesDirectory)\\'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: ArchiveFiles@2
  displayName: Create .NET 4.6 lpx
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/$(buildConfiguration)/net46'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Madd0.AzureStorageDriver.lpx'
    replaceExistingArchive: true

- task: ArchiveFiles@2
  displayName: Create .NET Core 3.1 lpx6
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/$(buildConfiguration)/netcoreapp3.1'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Madd0.AzureStorageDriver.netcore31.lpx6'
    replaceExistingArchive: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)/$(buildConfiguration)'
    Contents: |
      *.nupkg
      *.snupkg
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
